# golangci-lint configuration file
# This file shows how to configure linterlog with golangci-lint

linters-settings:
  custom:
    linterlog:
      path: ./bin/linterlog.so
      description: Linter for analyzing log statements in Go code
      original-url: github.com/andro-kes/linterlog

linters:
  enable:
    - linterlog
  disable-all: false

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
